INFO:src.api.package_route_api:Sending GET request to http://localhost:5000/reports/summary
ERROR:src.api.package_route_api:Error getting summary report: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /reports/summary (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff55b668ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
