{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /packages/ingest (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff55b8c3670>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Verify successful package ingestion and routing","uid":"155d91dbca89ea31","parentUid":"f89376a50affe2c622530ad3da9b9c39","status":"broken","time":{"start":1753794493101,"stop":1753794493129,"duration":28},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["Routing","API","HappyPath","Ingestion"]}],"uid":"f89376a50affe2c622530ad3da9b9c39"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /packages/ingest (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff55b68d4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Verify package ingestion with invalid image format","uid":"8e5d7c9e1cf6ccf","parentUid":"122d16cad598ec8410f2c9f3d0c4b558","status":"broken","time":{"start":1753794493276,"stop":1753794493278,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["Validation","NegativeTest","API"]}],"uid":"122d16cad598ec8410f2c9f3d0c4b558"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /packages/ingest (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff55b6ce340>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Verify ingestion with no image file provided","uid":"2834279d9c3c12d6","parentUid":"875fbdb424d91270e752af94e14e6a5d","status":"broken","time":{"start":1753794493387,"stop":1753794493389,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["Validation","NegativeTest","API"]}],"uid":"875fbdb424d91270e752af94e14e6a5d"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /packages/non-existent-package-id-123/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff55b8c3fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Verify retrieving status of a non-existent package","uid":"2860ed2370c3cdbb","parentUid":"bd7b96545e964b1beacabd9bdf2eed96","status":"broken","time":{"start":1753794493504,"stop":1753794493506,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["Status","NegativeTest","API"]}],"uid":"bd7b96545e964b1beacabd9bdf2eed96"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /reports/summary (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff55b668ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Verify summary report is retrievable","uid":"6e51722bcda2da1a","parentUid":"2add9cf39e7cfcb928c9159bca0dea37","status":"broken","time":{"start":1753794493612,"stop":1753794493614,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["Report","API","HappyPath"]}],"uid":"2add9cf39e7cfcb928c9159bca0dea37"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}